name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Node diagnostics
        run: |
          node -v
          pnpm -v || true

      - name: Enable corepack & install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies (pnpm)
        run: pnpm i

      - name: Build (pnpm)
        env:
          BASE_URL: "/ordboka.xyz/"
        run: |
          pnpm build

      - name: Generate static site (pnpm)
        run: pnpm run generate

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .output/public
          keep_files: false
